version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ''
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: ''
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: any
